import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import axios from "axios";
import { useState } from "react";

export default function Home() {
  const [file, setFile] = useState(null);

  const onSubmit = async () => {
    const url = "https://dev.lenna.ai/backend/api/auth/koptel/pengajuan/ktp";
    const formData = new FormData();
    formData.append("image", file);
    try {
      const response = await axios({
        method: "POST",
        url,
        data: formData,
        headers: {
          Auth: "INGNE-123token-verifikator",
        },
      });
      console.log(response);
    } catch (error) {
      console.log(error);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <input onChange={(e) => setFile(e)} type="file" />
        <button onClick={onSubmit}>Submit</button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
